# Generated by Django 4.2.1 on 2023-07-01 01:49

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_introduce_user_introduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name=builtins.id),
        ),
    ]
