# Generated by Django 4.2.1 on 2023-07-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_nickname_alter_user_email_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(default='이사 준비중입니다!', verbose_name='소개글'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='아기사자 33', max_length=255, verbose_name='닉네임'),
        ),
    ]
