# Generated by Django 4.2.1 on 2023-07-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_introduction_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(default='이사 준비 중입니다!', verbose_name='소개글'),
        ),
    ]
