# Generated by Django 4.2.1 on 2023-07-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='체크 여부'),
        ),
    ]
