# Generated by Django 4.2.1 on 2023-07-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_schedule_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='date',
            field=models.DateField(null=True, verbose_name='날짜'),
        ),
    ]
