# Generated by Django 4.2.2 on 2023-07-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationPost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='파일'),
        ),
    ]
