# Generated by Django 4.2.2 on 2023-07-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationPost', '0003_alter_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[], max_length=20, verbose_name='해당 게시물에 대한 topic'),
        ),
    ]
