# Generated by Django 4.2.2 on 2023-07-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationPost', '0005_alter_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='board_type',
            field=models.CharField(choices=[('information', '정보게시판'), ('review', '후기게시판'), ('hometown', '우리동네게시판')], max_length=20, verbose_name='게시판 종류'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='boards/files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boards/images/', verbose_name='이미지'),
        ),
    ]
