# Generated by Django 4.2.1 on 2023-07-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informationPost', '0005_alter_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='boards/files/', verbose_name='파일'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='boards/images/', verbose_name='이미지'),
        ),
    ]
